name: kashida_example
description: "Example app that uses the kashida package to find and insert tatweel"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  characters: ^1.4.1
  flutter:
    sdk: flutter
  kashida:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Naskh Arabic
      fonts:
        - asset: fonts/NotoNaskhArabic-Regular.ttf
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
    - family: Scheherazade New
      fonts:
        - asset: fonts/ScheherazadeNew-Regular.ttf
    - family: Lateef
      fonts:
        - asset: fonts/Lateef-Regular.ttf
    - family: Noto Sans Arabic
      fonts:
        - asset: fonts/NotoSansArabic-Regular.ttf
    - family: Noto Kufi Arabic
      fonts:
        - asset: fonts/NotoKufiArabic-Regular.ttf
    - family: Noto Nastaliq Urdu
      fonts:
        - asset: fonts/NotoNastaliqUrdu-Regular.ttf
    - family: Noto Sans Syriac
      fonts:
        - asset: fonts/NotoSansSyriac-Regular.ttf
