// Unicode Joining_Type / Joining_Group lookups.
import 'joining_tables.dart';

enum JoiningType {
  nonJoining,
  dualJoining,
  rightJoining,
  leftJoining,
  joinCausing,
  transparent,
}

enum JoiningGroup {
  africanFeh,
  africanNoon,
  africanQaf,
  ain,
  alaph,
  alef,
  beh,
  beth,
  burushaskiYehBarree,
  dal,
  dalathRish,
  e,
  farsiYeh,
  fe,
  feh,
  finalSemkath,
  gaf,
  gamal,
  hah,
  hanifiRohingyaKinnaYa,
  hanifiRohingyaPa,
  he,
  heh,
  hehGoal,
  heth,
  kaf,
  kaph,
  kashmiriYeh,
  khaph,
  knottedHeh,
  lam,
  lamadh,
  malayalamBha,
  malayalamJa,
  malayalamLla,
  malayalamLlla,
  malayalamNga,
  malayalamNna,
  malayalamNnna,
  malayalamNya,
  malayalamRa,
  malayalamSsa,
  malayalamTta,
  manichaeanAleph,
  manichaeanAyin,
  manichaeanBeth,
  manichaeanDaleth,
  manichaeanDhamedh,
  manichaeanFive,
  manichaeanGimel,
  manichaeanHeth,
  manichaeanHundred,
  manichaeanKaph,
  manichaeanLamedh,
  manichaeanMem,
  manichaeanNun,
  manichaeanOne,
  manichaeanPe,
  manichaeanQoph,
  manichaeanResh,
  manichaeanSadhe,
  manichaeanSamekh,
  manichaeanTaw,
  manichaeanTen,
  manichaeanTeth,
  manichaeanThamedh,
  manichaeanTwenty,
  manichaeanWaw,
  manichaeanYodh,
  manichaeanZayin,
  meem,
  mim,
  noJoiningGroup,
  noon,
  nun,
  nya,
  pe,
  qaf,
  qaph,
  reh,
  reversedPe,
  rohingyaYeh,
  sad,
  sadhe,
  seen,
  semkath,
  shin,
  straightWaw,
  swashKaf,
  syriacWaw,
  tah,
  taw,
  tehMarbuta,
  tehMarbutaGoal,
  teth,
  thinNoon,
  thinYeh,
  verticalTail,
  waw,
  yeh,
  yehBarree,
  yehWithTail,
  yudh,
  yudhHe,
  zain,
  zhain,
}

const Map<String, JoiningGroup> joiningGroupLongNames = {
  'African_Feh': JoiningGroup.africanFeh,
  'African_Noon': JoiningGroup.africanNoon,
  'African_Qaf': JoiningGroup.africanQaf,
  'Ain': JoiningGroup.ain,
  'Alaph': JoiningGroup.alaph,
  'Alef': JoiningGroup.alef,
  'Beh': JoiningGroup.beh,
  'Beth': JoiningGroup.beth,
  'Burushaski_Yeh_Barree': JoiningGroup.burushaskiYehBarree,
  'Dal': JoiningGroup.dal,
  'Dalath_Rish': JoiningGroup.dalathRish,
  'E': JoiningGroup.e,
  'Farsi_Yeh': JoiningGroup.farsiYeh,
  'Fe': JoiningGroup.fe,
  'Feh': JoiningGroup.feh,
  'Final_Semkath': JoiningGroup.finalSemkath,
  'Gaf': JoiningGroup.gaf,
  'Gamal': JoiningGroup.gamal,
  'Hah': JoiningGroup.hah,
  'Hanifi_Rohingya_Kinna_Ya': JoiningGroup.hanifiRohingyaKinnaYa,
  'Hanifi_Rohingya_Pa': JoiningGroup.hanifiRohingyaPa,
  'He': JoiningGroup.he,
  'Heh': JoiningGroup.heh,
  'Heh_Goal': JoiningGroup.hehGoal,
  'Heth': JoiningGroup.heth,
  'Kaf': JoiningGroup.kaf,
  'Kaph': JoiningGroup.kaph,
  'Kashmiri_Yeh': JoiningGroup.kashmiriYeh,
  'Khaph': JoiningGroup.khaph,
  'Knotted_Heh': JoiningGroup.knottedHeh,
  'Lam': JoiningGroup.lam,
  'Lamadh': JoiningGroup.lamadh,
  'Malayalam_Bha': JoiningGroup.malayalamBha,
  'Malayalam_Ja': JoiningGroup.malayalamJa,
  'Malayalam_Lla': JoiningGroup.malayalamLla,
  'Malayalam_Llla': JoiningGroup.malayalamLlla,
  'Malayalam_Nga': JoiningGroup.malayalamNga,
  'Malayalam_Nna': JoiningGroup.malayalamNna,
  'Malayalam_Nnna': JoiningGroup.malayalamNnna,
  'Malayalam_Nya': JoiningGroup.malayalamNya,
  'Malayalam_Ra': JoiningGroup.malayalamRa,
  'Malayalam_Ssa': JoiningGroup.malayalamSsa,
  'Malayalam_Tta': JoiningGroup.malayalamTta,
  'Manichaean_Aleph': JoiningGroup.manichaeanAleph,
  'Manichaean_Ayin': JoiningGroup.manichaeanAyin,
  'Manichaean_Beth': JoiningGroup.manichaeanBeth,
  'Manichaean_Daleth': JoiningGroup.manichaeanDaleth,
  'Manichaean_Dhamedh': JoiningGroup.manichaeanDhamedh,
  'Manichaean_Five': JoiningGroup.manichaeanFive,
  'Manichaean_Gimel': JoiningGroup.manichaeanGimel,
  'Manichaean_Heth': JoiningGroup.manichaeanHeth,
  'Manichaean_Hundred': JoiningGroup.manichaeanHundred,
  'Manichaean_Kaph': JoiningGroup.manichaeanKaph,
  'Manichaean_Lamedh': JoiningGroup.manichaeanLamedh,
  'Manichaean_Mem': JoiningGroup.manichaeanMem,
  'Manichaean_Nun': JoiningGroup.manichaeanNun,
  'Manichaean_One': JoiningGroup.manichaeanOne,
  'Manichaean_Pe': JoiningGroup.manichaeanPe,
  'Manichaean_Qoph': JoiningGroup.manichaeanQoph,
  'Manichaean_Resh': JoiningGroup.manichaeanResh,
  'Manichaean_Sadhe': JoiningGroup.manichaeanSadhe,
  'Manichaean_Samekh': JoiningGroup.manichaeanSamekh,
  'Manichaean_Taw': JoiningGroup.manichaeanTaw,
  'Manichaean_Ten': JoiningGroup.manichaeanTen,
  'Manichaean_Teth': JoiningGroup.manichaeanTeth,
  'Manichaean_Thamedh': JoiningGroup.manichaeanThamedh,
  'Manichaean_Twenty': JoiningGroup.manichaeanTwenty,
  'Manichaean_Waw': JoiningGroup.manichaeanWaw,
  'Manichaean_Yodh': JoiningGroup.manichaeanYodh,
  'Manichaean_Zayin': JoiningGroup.manichaeanZayin,
  'Meem': JoiningGroup.meem,
  'Mim': JoiningGroup.mim,
  'No_Joining_Group': JoiningGroup.noJoiningGroup,
  'Noon': JoiningGroup.noon,
  'Nun': JoiningGroup.nun,
  'Nya': JoiningGroup.nya,
  'Pe': JoiningGroup.pe,
  'Qaf': JoiningGroup.qaf,
  'Qaph': JoiningGroup.qaph,
  'Reh': JoiningGroup.reh,
  'Reversed_Pe': JoiningGroup.reversedPe,
  'Rohingya_Yeh': JoiningGroup.rohingyaYeh,
  'Sad': JoiningGroup.sad,
  'Sadhe': JoiningGroup.sadhe,
  'Seen': JoiningGroup.seen,
  'Semkath': JoiningGroup.semkath,
  'Shin': JoiningGroup.shin,
  'Straight_Waw': JoiningGroup.straightWaw,
  'Swash_Kaf': JoiningGroup.swashKaf,
  'Syriac_Waw': JoiningGroup.syriacWaw,
  'Tah': JoiningGroup.tah,
  'Taw': JoiningGroup.taw,
  'Teh_Marbuta': JoiningGroup.tehMarbuta,
  'Teh_Marbuta_Goal': JoiningGroup.tehMarbutaGoal,
  'Teth': JoiningGroup.teth,
  'Thin_Noon': JoiningGroup.thinNoon,
  'Thin_Yeh': JoiningGroup.thinYeh,
  'Vertical_Tail': JoiningGroup.verticalTail,
  'Waw': JoiningGroup.waw,
  'Yeh': JoiningGroup.yeh,
  'Yeh_Barree': JoiningGroup.yehBarree,
  'Yeh_With_Tail': JoiningGroup.yehWithTail,
  'Yudh': JoiningGroup.yudh,
  'Yudh_He': JoiningGroup.yudhHe,
  'Zain': JoiningGroup.zain,
  'Zhain': JoiningGroup.zhain,
};

JoiningType joiningTypeOf(int codepoint) {
  var lo = 0;
  var hi = joiningTypeRangeStarts.length - 1;
  while (lo <= hi) {
    final mid = (lo + hi) >> 1;
    if (codepoint < joiningTypeRangeStarts[mid]) {
      hi = mid - 1;
    } else if (codepoint > joiningTypeRangeEnds[mid]) {
      lo = mid + 1;
    } else {
      return joiningTypeRangeValues[mid];
    }
  }
  return JoiningType.nonJoining;
}

JoiningGroup joiningGroupOf(int codepoint) {
  var lo = 0;
  var hi = joiningGroupCodepoints.length - 1;
  while (lo <= hi) {
    final mid = (lo + hi) >> 1;
    final cp = joiningGroupCodepoints[mid];
    if (codepoint < cp) {
      hi = mid - 1;
    } else if (codepoint > cp) {
      lo = mid + 1;
    } else {
      return joiningGroupValues[mid];
    }
  }
  return JoiningGroup.noJoiningGroup;
}

